minimum_pre_commit_version: "3.6.0"

default_language_version:
  python: python3.12

exclude: |
  (?x)^(
    \.git/
    | \.venv/|venv/|env/
    | \.pytest_cache/
    | build/|dist/
    | .*\.egg-info/
    | reports/
  )$

repos:
  # Ruff: lint + isort autofix
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        name: ruff (lint + autofix)
        args: [--fix, --exit-non-zero-on-fix]
        files: ^(src|tests)/.*\.py$

  # Black: single source of truth for formatting
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3.12
        files: ^(src|tests)/.*\.py$

  # MyPy: reads config from pyproject [tool.mypy]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        name: mypy (src only)
        files: ^src/.*\.py$
        additional_dependencies:
          - types-setuptools

  # Bandit: security linter (pre-push)
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        name: bandit (src only)
        args: [-q, -r, src, -x, tests]
        stages: [pre-push]
        pass_filenames: false

  # pip-audit: project deps only (pre-push), isolated in hook venv
  - repo: local
    hooks:
      - id: pip-audit
        name: pip-audit (project deps only, pre-push)
        language: python
        additional_dependencies:
          - pip-audit
        entry: bash -lc 'pip install -q -e .[dev] || pip install -q -e .; pip-audit'
        stages: [pre-push]
        pass_filenames: false

  # Core sanity hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: detect-private-key
      - id: check-added-large-files
