name: Deploy Documentation (mike)

on:
  push:
    branches: [main, master]
    tags: ["v*.*.*"]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "pages-mike"
  cancel-in-progress: false

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history for mike)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Use SSH deploy key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY_KEY }}

      - name: Point origin to SSH remote
        run: |
          git remote set-url origin "git@github.com:${{ github.repository }}.git"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # на всякий случай подтянем теги
          git fetch --tags --force --prune

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install doc deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install mkdocs mkdocs-material mkdocstrings[python] ruff mike

      - name: Build check (strict)
        run: mkdocs build --clean --strict

      # Snapshot main → "dev" (без latest)
      - name: Deploy dev (main)
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          mike deploy --push --remote origin --branch gh-pages dev
          # default оставим latest — установится/переустановится на релизе
          mike set-default --push --remote origin latest || true

      # Tag release → версия = имя тега, alias latest обновляется
      - name: Deploy release (tag)
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          TAG: ${{ github.ref_name }}   # e.g. v1.2.3
        run: |
          mike deploy --push --remote origin --branch gh-pages "${TAG}" latest
          mike set-default --push --remote origin latest
